pub rec Bool = enum { False, True };
open Bool;
export Bool;
pub syntax if { if ($c) $(t : Block) else $(e : Block) => match ($c) { True => $t, False => $e } };
pub i64_to_bool = fn(n) { match (n) { 0 => False, _ => True } };
pub rec Option = fn(A : Type) { enum { Some(A), None } };
open Option;
export Option;
pub rec List = fn(A : Type) { enum { Nil, Cons(A, List(A)) } };
open List;
export List;
pub Syntax = module {
  pub rec Explicitness = enum { Explicit, Implicit };
  export Explicitness;
  pub rec Assoc = enum { Left, Right, NonAssoc };
  export Assoc;

  pub Span = struct {file: Option(String); start_byte: I64; end_byte: I64; start_line: Option(I64); start_col: Option(I64); end_line: Option(I64); end_col: Option(I64)};

  pub Id = struct {name: String; span: Option(Span); scope: Scopes};

  pub PathChoice = struct {opens: List(String); fallback: Option(String)};
  pub Path = struct {head: Id; members: List(String); head_choice: Option(PathChoice)};
  pub rec AtomVal = enum { I64Atom(I64), CharAtom(Char), StringAtom(String), UnitAtom, ScopesAtom(Scopes) };
  export AtomVal;
  pub rec AtomTy = enum { TyI64, TyUnit, TyChar, TyString, TyScopes, TyAbsurd };
  export AtomTy;
  pub rec Fixity = enum { PrefixFixity, InfixFixity };
  export Fixity;
  pub rec MacroAnn = enum { AnnExpr, AnnDecl };
  export MacroAnn;
  pub rec Expr = enum { RawVar(Option(Span), Id), RawAtom(Option(Span), AtomVal), RawSelf(Option(Span)), RawSelfType(Option(Span)), RawAp(Option(Span), Expr, Explicitness, Expr), RawLam(Option(Span), Param, Expr), RawLet(Option(Span), Id, Option(Expr), Expr, Expr, Bool), RawLetRecGroup(Option(Span), List(Id), List(Expr), Expr), RawAnnotated(Option(Span), Expr, Expr), RawProd(Option(Span), List(Expr)), RawProdTy(Option(Span), List(Expr)), RawTraitBoundSet(Option(Span), List(Expr)), RawArrow(Option(Span), Explicitness, Option(Id), Expr, Option(EffectRow), Expr), RawFieldAccess(Option(Span), Expr, String), RawProj(Option(Span), Expr, I64), RawRecordConstruct(Option(Span), Expr, List(Field)), RawStruct(Option(Span), List(Decl)), RawModule(Option(Span), List(Decl)), RawSig(Option(Span), List(Decl)), RawEnum(Option(Span), Option(String), List(Ctor)), RawImport(Option(Span), String, Scopes), RawOpen(Option(Span), Expr, Expr, String), RawOpenChoice(Option(Span), Id, List(String), Option(String)), RawTypeDef(Option(Span), TypeDecl, Expr), RawEffectDef(Option(Span), Id, List(Id), List(EffectOp), Expr), RawTraitDef(Option(Span), Id, List(Id), List(Field), Expr), RawImplDef(Option(Span), Option(Id), Path, List(Expr), List(Field), Expr), RawPerform(Option(Span), Path, Expr), RawResume(Option(Span), Expr), RawRefNew(Option(Span), Expr), RawRefGet(Option(Span), Expr), RawRefSet(Option(Span), Expr, Expr), RawMatch(Option(Span), Expr, List(Branch)), RawStx(Option(Span), Expr), RawQuote(Option(Span), Expr, List(QuoteHole)), RawQuoteDecls(Option(Span), List(Decl), List(QuoteHole)), RawMacroDef(Option(Span), Id, Expr, Expr, Option(MacroAnn), Option(Expr)), RawSyntaxDef(Option(Span), Id, Role, Expr), RawBlock(Option(Span), List(TokenTree)), RawInstantiate(Option(Span), Id, Rule, List(Capture), Option(String)), RawMacroCall(Option(Span), Expr, List(Captured)), RawOperatorUse(Option(Span), Id, Fixity, List(Expr), Option(Span), Option(Span), Option(String)) } and TokenTree = enum { Tok(Option(Span), TokenKind, Scopes), TokGroup(Option(Span), Delim, List(TokenTree)) } and TokenKind = enum { IdentTok(String), OperatorTok(String), IntTok(I64), CharTok(Char), StringTok(String), UnitTok, KeywordTok(String), PunctTok(String) } and Delim = enum { ParenDelim, BracketDelim, BraceDelim } and Role = enum { MkRole(Fixity, Option(Order), RoleMeaning, Option(Span), Option(String)) } and Order = enum { MkOrder(String, String, Assoc, Bool, List(Order), List(Order)) } and RoleMeaning = enum { ApplyValue, AssignRef, CallMacro, Rules(MacroAnn, List(Rule)), OrderGroup, PolyArrow } and Rule = enum { MkRule(List(RulePart), Replacement, Option(Span)) } and RulePart = enum { PartToken(TokenTree), PartGroup(Delim, List(RulePart), Option(Span)), PartHole(String, HoleKind, Option(Span)) } and HoleKind = enum { HoleExpr, HoleBlock, HoleId, HoleDecl, HoleOneDecl, HolePattern, HoleTokens } and Replacement = enum { ReplaceExpr(Expr), ReplaceDecls(List(Decl)) } and Capture = enum { MkCapture(String, Captured) } and Captured = enum { CapExpr(Expr), CapBlock(List(TokenTree)), CapId(TokenTree), CapPattern(Pattern), CapDecls(List(Decl)), CapDecl(Decl), CapTokens(List(TokenTree)) } and Field = enum { MkField(String, Expr) } and QuoteHole = enum { MkQuoteHole(String, Expr) } and Param = enum { MkParam(Id, Option(Expr), List(Path), Explicitness) } and EffectRow = enum { MkEffectRow(List(Expr), List(Expr), Bool, Bool) } and EffectOp = enum { MkEffectOp(String, Expr, Expr) } and TypeDecl = enum { MkTypeDecl(Id, List(Id), List(Ctor)) } and Ctor = enum { MkCtor(Id, List(Expr)) } and Branch = enum { ValueBranch(Pattern, Expr), EffectBranch(Path, Pattern, Expr) } and Pattern = enum { RawPatWild(Option(Span)), RawPatBind(Option(Span), Id), RawPatCon(Option(Span), Path, List(Pattern)), RawPatAtom(Option(Span), AtomVal), RawPatProd(Option(Span), List(Pattern)), RawPatOr(Option(Span), Pattern, Pattern), RawPatRecord(Option(Span), Path, List(PatField), Bool), RawPatStructType(Option(Span), List(PatField), Bool), RawPatType(Option(Span), AtomTy) } and PatField = enum { MkPatField(String, Option(Pattern)) } and Decl = enum { DeclLet(Id, Expr, Bool, Bool), DeclRecGroup(List(Id), List(Expr), Bool), DeclMethod(Id, List(Param), Option(EffectRow), Expr, Bool), DeclEffect(Id, List(Id), List(EffectOp), Bool), DeclTrait(Id, List(Id), List(Field), Bool), DeclImpl(Option(Id), Path, List(Expr), List(Field), Bool), DeclMacro(Id, Expr, Bool, Option(MacroAnn), Option(Expr)), DeclMacroCall(Expr, List(Captured), Bool), DeclPatternSyn(Id, List(Id), Pattern, Bool), DeclField(String, Expr), DeclOpen(Expr, String), DeclExport(Expr, Option(List(String)), Bool), DeclHole(Id), DeclSyntax(Id, Role, Bool), DeclItems(List(TokenTree)), DeclInstantiate(Id, Rule, List(Capture), Option(String), Bool) };
  export Expr;
  export TokenTree;
  export TokenKind;
  export Delim;
  export Role;
  export Order;
  export RoleMeaning;
  export Rule;
  export RulePart;
  export HoleKind;
  export Replacement;
  export Capture;
  export Captured;
  export Field;
  export QuoteHole;
  export Param;
  export EffectRow;
  export EffectOp;
  export TypeDecl;
  export Ctor;
  export Branch;
  export Pattern;
  export PatField;
  export Decl;
  pub pattern Var(name) = Expr.RawVar(_, name);
  pub pattern Ap(f, a) = Expr.RawAp(_, f, _, a);
  pub pattern Lam(name, body) = Expr.RawLam(_, name, body);
  pub pattern Let(name, val, body) = Expr.RawLet(_, name, _, val, body, _);
  pub pattern Atom(val) = Expr.RawAtom(_, val);
  pub TypeExpr : Type = Type;
  pub pat_wild = Pattern.RawPatWild(None);
  pub pat_var = fn(id) { Pattern.RawPatBind(None, id) };
  pub pat_con = fn(name, args) { Pattern.RawPatCon(None, Path{head = name; members = Nil; head_choice = None}, args) };
  pub pat_atom = fn(val) { Pattern.RawPatAtom(None, val) };
  pub pat_prod = fn(pats) { Pattern.RawPatProd(None, pats) };
  pub pat_or = fn(l, r) { Pattern.RawPatOr(None, l, r) };
  pub pattern PatWild = Pattern.RawPatWild(_);
  pub pattern PatBind(name) = Pattern.RawPatBind(_, name);
  pub pattern PatCon(path, args) = Pattern.RawPatCon(_, path, args);
  pub pattern PatAtom(val) = Pattern.RawPatAtom(_, val);
  pub pattern PatProd(pats) = Pattern.RawPatProd(_, pats);
  pub pattern PatOr(l, r) = Pattern.RawPatOr(_, l, r);
  pub Decls = List(Decl);
  pub decl_let = fn(name, val, is_pub) { Decl.DeclLet(name, val, is_pub, False) };
  pub rec R = enum { RExpr(Type), RDecls, RPat };
  export R;
  pub atom_val = fn(val) { Expr.RawAtom(None, val) };
  pub ap = fn(f, a) { Expr.RawAp(None, f, Explicitness.Explicit, a) };
  pub i64 = fn(n) { atom_val(AtomVal.I64Atom(n)) };
  pub string = fn(s) { atom_val(AtomVal.StringAtom(s)) };
  pub char = fn(c) { atom_val(AtomVal.CharAtom(c)) };
  pub unit = fn(_) { atom_val(AtomVal.UnitAtom) };
  pub tokens = fn(b : Expr) { match (b) { Expr.RawBlock(_, ts) => ts, _ => panic[List(TokenTree)]("tokens: not a block") } };
  pub expand_block = fn(b : Expr) { expand_block[Expr](b) };
  pub expand_decls = fn(d : Decls) { expand_decls[Decls](d) };
  pub id_name = fn(stx) { match (stx) { Expr.RawVar(_, id) => id.name, _ => panic[String]("expected identifier") } };
  pub id_eq = fn(a, b) { match (a) { Expr.RawVar(_, ida) => match (b) { Expr.RawVar(_, idb) => i64_to_bool(eq_string(ida.name, idb.name)), _ => panic[Bool]("expected identifier") }, _ => panic[Bool]("expected identifier") } }

}
